### ISSUE TITLE
关于数据集JSON文件格式

### ISSUE THREAD

**Issue by XiangzhuKong** [JusperLee/SPMamba#10]
您好，请问数据集的JSON格式是什么？应该怎么准备？

**Comment by JusperLee** [comment]
[mix_clean.json](https://github.com/user-attachments/files/15981795/mix_clean.json)
[s1.json](https://github.com/user-attachments/files/15981798/s1.json)
[s2.json](https://github.com/user-attachments/files/15981799/s2.json)
