### ISSUE TITLE
数据集缺少mix.son

### ISSUE THREAD

**Issue by theneao** [JusperLee/SPMamba#19]
发布的数据集缺少对应的配置文件，如下
![图片](https://github.com/user-attachments/assets/d9c5fcb4-456b-4ed4-819f-0a8986e29e9a)
看了其他issue也不太理解json内容是什么，为了方便测试和运行，还请把数据集的对应json发一下，或者描述下json如何制作

**Comment by JusperLee** [comment]
https://github.com/JusperLee/SPMamba/blob/main/process_echoset.py
