### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'DataPreProcess/Echo2Mix/train/mix.json'

### ISSUE THREAD

**Issue by yaodada1** [JusperLee/SPMamba#20]
从首页提供的Echo2Mix数据集下载后train、val、test三个文件夹下都没有mix.json文件。。

**Comment by JusperLee** [comment]
你需要自己构建这个文件。请查阅https://github.com/JusperLee/SPMamba/blob/main/process_echoset.py

**Comment by yaodada1** [comment]
> 你需要自己构建这个文件。请查阅https://github.com/JusperLee/SPMamba/blob/main/process_echoset.py

好的我试试，数据集内的音频测试效果没什么问题，但泛化能力好像不太行，我测自己混合的两人数据，分离不出来，是哪里有问题吗？
[6.zip](https://github.com/user-attachments/files/18235460/6.zip)

**Comment by JusperLee** [comment]
这个应该是数据集的泛化能力，你可能需要更符合你自己数据的数据集。

**Comment by yaodada1** [comment]
> 这个应该是数据集的泛化能力，你可能需要更符合你自己数据的数据集。

是，我在两个模型上都测了我这批数据，SPMamba-Librimix的模型在两人重叠数据上效果可以接受的。SPMamba-Echo2Mix的模型效果不太行。
